[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
"npm:corepack" = "latest"

[tasks.setup]
depends = ["setup:*"]
description = "Set up the dev environment"

[tasks."setup:pnpm"]
run = "pnpm install"
hide = true
description = "Install dependencies with pnpm"
