name: Publish Preview Prettier Config Package
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
        - 'packages/prettier-config/**'
        - 'package.json'
        - 'pnpm-lock.yaml'
        - '.github/workflows/pkg-pr-new-prettier.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:prettier

      - name: Publish Preview Package
        run: pnpm run pkg-pr-new:prettier
