name: Publish Preview Package
on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened
    paths:
        - 'packages/**'
        - 'package.json'
        - 'pnpm-lock.yaml'
        - '.github/workflows/pkg-pr-new.yml'

jobs:
  paths-filter:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    timeout-minutes: 5
    outputs:
      eslint: ${{ steps.filter.outputs.eslint-config }}
      prettier: ${{ steps.filter.outputs.prettier-config }}
      stylelint: ${{ steps.filter.outputs.stylelint-config }}
      tsconfig: ${{ steps.filter.outputs.tsconfig }}
      directory: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            eslint-config:
              - 'packages/eslint-config/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
            prettier-config:
              - 'packages/prettier-config/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
            stylelint-config:
              - 'packages/stylelint-config/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
            tsconfig:
              - 'packages/tsconfig/**'
              - 'package.json'
              - 'pnpm-lock.yaml'

  publish:
    needs: paths-filter
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    env:
      eslint: './packages/eslint-config'
      prettier: './packages/prettier-config'
      stylelint: './packages/stylelint-config'
      tsconfig: './packages/tsconfig'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - if: ${{ needs.paths-filter.outputs.eslint == 'true' }}
        name: Build ESLint Config Package
        run: pnpm build:eslint

      - if: ${{ needs.paths-filter.outputs.prettier == 'true' }}
        name: Build Prettier Config Package
        run: pnpm build:prettier

      - if: ${{ needs.paths-filter.outputs.stylelint == 'true' }}
        name: Build Stylelint Config Package
        run: pnpm build:stylelint

      - if: ${{ needs.paths-filter.outputs.eslint == 'true' || needs.paths-filter.outputs.prettier == 'true' || needs.paths-filter.outputs.stylelint == 'true' || needs.paths-filter.outputs.tsconfig == 'true' }}
        name: Publish Preview Package
        shell: bash
        # needs.paths-filter.outputs.directory には eslint-config | prettier-config | stylelint-config | tsconfig を要素とするJSON配列の文字列が入っている
        # が、"["eslint-config","prettier-config","stylelint-config","tsconfig"]" のようになっているため、無理やり文字列にして直したあとにjqでパースする

        run: |
          RAW_DIRS="${{ needs.paths-filter.outputs.directory }}"
          read -ra PACKAGE_DIRS < <(jq -r -c 'split(",") | map("./packages/" + .) | join(" ")' <<<"\"${RAW_DIRS:1:-1}\"")
          pnpm run pkg-pr-new "${PACKAGE_DIRS[@]}"
